##Dockerfile

#Base images 基础镜像
FROM ubuntu:18.04

##MAINTAINER 维护者信息
maintainer sxl Carl3633524461@outlook.com

#RUN 执行以下命令
RUN apt update
RUN apt install python3 python3-pip
RUN pip3 iinstall flask
RUN mkdir -p /date/www/

#拷贝文件到工作目录
COPY app.py /date/www/app.py

#工作目录文件
WORKDIR /date/www/
RUN git clone
#EXPOSE 映射端口
EXPOSE 80

#容器启动时执行命令
CMD ["python3","app.py"]

